{{- if (not .Values.dnsimple.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dnsimple-cron-updater.secretName" . }}
  labels:
    {{- include "dnsimple-cron-updater.labels" . | nindent 4 }}
type: Opaque
data:
  {{ required "A valid .Values.dnsimple.secret.tokenKey entry required!" .Values.dnsimple.secret.tokenKey | quote }}: {{ required "A valid .Values.dnsimple.token entry required!" .Values.dnsimple.token | toString | b64enc | quote }}
  {{ required "A valid .Values.dnsimple.secret.accountIdKey entry required!" .Values.dnsimple.secret.accountIdKey | quote }}: {{ required "A valid .Values.dnsimple.accountId entry required!" .Values.dnsimple.accountId | toString | b64enc | quote }}
  {{ required "A valid .Values.dnsimple.secret.zoneIdKey entry required!" .Values.dnsimple.secret.zoneIdKey | quote }}: {{ required "A valid .Values.dnsimple.zoneId entry required!" .Values.dnsimple.zoneId | toString | b64enc | quote }}
  {{ required "A valid .Values.dnsimple.secret.recordIdKey entry required!" .Values.dnsimple.secret.recordIdKey | quote }}: {{ required "A valid .Values.dnsimple.recordId entry required!" .Values.dnsimple.recordId | toString | b64enc | quote }}
{{- end }}
